#!/bin/sh

set -e

if [ -z "$OS" ]; then
  echo "\$OS should be Linux, Darwin, or Win64"
  exit 1
fi

if [ $OS = "Linux" -o $OS = "Darwin" ]; then
	cd sdl
	./configure
	make build/libSDL2.la
	cd ..
	rm -rf lib
	mkdir lib
	if [ $OS = "Linux" ]; then
		cp sdl/build/.libs/libSDL2-*.so.*.*.* lib
		sdl=`ls lib`
		link=`echo $sdl | sed -E 's/(so\.[0-9]*).*/\1/'`
		link2="libSDL2.so"
	else
		cp sdl/build/.libs/libSDL2-*.*.*.dylib lib
		sdl=`ls lib`
		link=`echo $sdl | sed -E 's/(-[0-9]*).*(\.dylib)/\1\2/'`
		link2="libSDL2.dylib"
	fi
	cd lib
	ln -s "$sdl" "$link"
	ln -s "$sdl" "$link2"
	cd ..
	cd glew
	make all
	cd ..
fi

if [ $OS = "Win64" ]; then
	OS_FLAGS="--host=x86_64-w64-mingw32 --disable-pthreads"
else
	OS_FLAGS=""
fi

cd curl
./configure \
    --enable-static --disable-shared --without-ssl \
    --without-libpsl --without-zstd --without-brotli \
    --without-libidn2 --without-librtmp \
    --without-zlib --without-nghttp2 --disable-ldap $OS_FLAGS
make -C lib
cd ..

if [ $OS = "Win64" ]; then
	make PORTABLE=1 OS=Windows CPU=x86_64 clean all
	SDLDLLPATH=sdl/x86_64-w64-mingw32/bin
else
	make PORTABLE=1 clean all
	SDLDLLPATH=sdl/i686-w64-mingw32/bin
fi

if [ $OS = "Win64" ]; then
	binaries="dis.exe zdis.exe vgmplay.exe blastem.exe $SDLDLLPATH/SDL2.dll"
else
	binaries="dis zdis vgmplay blastem termhelper lib"
fi

dir="blastem-0.6.2-kinetoscope"
rm -rf "$dir"
mkdir "$dir"

cp -r $binaries shaders images default.cfg rom.db gamecontrollerdb.txt systems.cfg "$dir"
for file in README COPYING CHANGELOG; do
	cp "$file" "$dir"/"$file".txt
done
cp sdl/LICENSE.txt "$dir"/SDL-LICENSE.txt
cp glew/LICENSE.txt "$dir"/GLEW-LICENSE.txt
